services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  migrate:
    build: .                      # your app image (has alembic + your code)
    command: alembic upgrade head
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy   # wait until Postgres actually accepts connections
    restart: "no"                    # run once, then exit

  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      migrate:
        condition: service_completed_successfully   # app starts only after migrate exits 0
    ports:
      - 8000:8000

  test:
    build: .
    command: pytest tests -v
    profiles: ["test"]
    env_file:
      - .env
    environment:
      APP_ENV: test
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB_TESTING}
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

volumes:
  postgres_data: