"""Chamge pokemon name for id

Revision ID: 82d19906a246
Revises: 4025f2db2fad
Create Date: 2026-07-16 18:27:17.038670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d19906a246'
down_revision: Union[str, Sequence[str], None] = '4025f2db2fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('pokemon_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_pokemon_pokemon_id'), 'pokemon', ['pokemon_id'], unique=False)
    op.drop_column('pokemon', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_pokemon_pokemon_id'), table_name='pokemon')
    op.drop_column('pokemon', 'pokemon_id')
    # ### end Alembic commands ###
